# Generated by Django 3.1.5 on 2021-01-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendee_info', serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('cumulative', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('ref_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=120)),
                ('page_link', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('balance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club_owner', to='tracker.balance')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ref_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('page_link', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('balance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_owner', to='tracker.balance')),
                ('organizers', models.ManyToManyField(related_name='events', to='tracker.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendee_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='tracker.attendee')),
                ('event_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='tracker.event')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendee_owner', to='tracker.balance'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='clubs',
            field=models.ManyToManyField(related_name='members', to='tracker.Club'),
        ),
    ]
